import Provider from "@/context/AuthContext";
import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/RootLayout/Header";

import { Providers } from "./provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Provider>
        <body className={inter.className + " relative"}>
          {/* Header */}
          <div className=" border-4 w-full ">
            <Header />
          </div>
          {/* Body */}
          <Providers>{children}</Providers>
        </body>
      </Provider>
    </html>
  );
}
